{% set name = "chemdyg" %}
{% set version = "0.1.2rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/ChemDyg/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5cfac1210996647b5c98700c92b0cd7ff7b4a3106349f788dcaba9d4fbb9191a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cartopy
    - matplotlib-base
    - netcdf4
    - numpy
    - pandas
    - scipy
    - xarray
    - zppy >=2.2.0

test:
  imports:
    - chemdyg
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/E3SM-Project/ChemDyg
  summary: 'Chemistry Diagnostics Package'
  description: |
    E3SM chemistry diagnostic package (ChemDyg) is designed for
    E3SM chemistry development, including plots and tables for model-to-model and model-to-observation comparison.

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/E3SM-Project/ChemDyg
  dev_url: https://github.com/E3SM-Project/ChemDyg

extra:
  recipe-maintainers:
    - xylar
    - hsiangheleellnl
    - tangq
